---
title: "Container"
author: "Ivan Jacob Agaloos Pesigan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Container}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
#| include = FALSE
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/vignettes-"
)
```

```{r}
#| include = FALSE
root <- rprojroot::is_rstudio_project
source(
  knitr::purl(
    root$find_file(
      "vignettes",
      "000-packages.Rmd"
    ),
    quiet = TRUE
  )
)
unlink("000-packages.R")
```

**[Docker](https://www.docker.com/) is required to build the container described below.**

You can use a [Rocker](https://rocker-project.org/) container containing the versions of `betaDelta` and `betaSandwich` used in Pesigan, Sun, & Cheung (2023) with:

```bash
docker run --rm -ti -e PASSWORD=yourpassword -p 8787:8787 jeksterslab/manbetaciwald-rocker
```

Open `http://localhost:8787` on your web browser to launch `Rstudio Server`.

- username: rstudio
- password: yourpassword

See [https://github.com/jeksterslab/docker-manbetaciwald-rocker](https://github.com/jeksterslab/docker-manbetaciwald-rocker) for more information on the container.
